server:
  port: 8182

spring:
  application:
    name: API-GATEWAY

  cloud:
    gateway:
      routes:
        - id: ORDER-SERVICE
          uri: lb://ORDER-SERVICE
          predicates:
            - Path=/orders/**

        - id: REPORT-SERVICE
          uri: lb://REPORT-SERVICE
          predicates:
            - Path=/reports/**

        - id: MARKET-SERVICE
          uri: lb://MARKET-SERVICE
          predicates:
            - Path=/shares/**

eureka:
  instance:
    prefer-ip-address: true
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: http://localhost:8181/eureka